# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(db_index=True, max_length=50, verbose_name='Фамилия')),
                ('patr_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('birth', models.CharField(max_length=4, verbose_name='Год рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Author_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TNBooks.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('annotation', models.CharField(max_length=255, verbose_name='Аннотация')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Genre_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TNBooks.Books')),
                ('id_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TNBooks.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('address', models.CharField(max_length=70, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TNBooks.Publishing_house'),
        ),
        migrations.AddField(
            model_name='author_books',
            name='id_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TNBooks.Books', verbose_name='Книга'),
        ),
    ]
